version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jordi-sapes"
s3_bucket = "sandbox-eu-west-one-udl"
s3_prefix = "udlpractices"
region = "eu-west-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
